sudo: required
services:
  - docker

before_install:
  - docker build -t iliyakarin/docker-react -f Dockerfile.dev .

script:
  - docker run iliyakarin/docker-react npm run test -- --coverage
