sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t iliyakarin/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true iliyakarin/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-react-ikarin"
  env: "DockerReactIkarin-env"
  bucket_name: "elasticbeanstalk-eu-north-1-804066141946"
  bucket_path: "docker-react-ikarin"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
